on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  create-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Create a comment in Asana Task
    steps:
      - name: Create a comment
        uses: Asana/comment-on-task-github-action@v1.2
        id: createComment
        with:
          asana-secret: ${{ secrets.5B7IODI7YILCQY2PRYWQQNCSCYYXY4D4QXTH5KJYTOVRRQOINARCJBNW }}
          comment-text: "https://github.com/JohanaS/Example-poem/pulls"
      - name: Get status
        run: echo "Status is ${{ steps.createComment.outputs.status }}"
